name: exports
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/masreplay/exports

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  glob: ^2.1.2
  path: ^1.8.0
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
